const { app } = require("@azure/functions");
const { TableClient, AzureNamedKeyCredential } = require("@azure/data-tables");
const crypto = require("crypto");
const TABLE = "VolleybalSync";
function clean(v,max){return String(v||"").trim().slice(0,max);}
function client(){const cs=process.env.VOLLEYBALL_STORAGE_CONNECTION;if(!cs)throw new Error("VOLLEYBALL_STORAGE_CONNECTION ontbreekt");return TableClient.fromConnectionString(cs,TABLE);}
function identity(req){const team=clean(req.headers.get("x-team-id"),80),key=clean(req.headers.get("x-sync-key"),160);if(!team||key.length<8)return null;const salt=process.env.SYNC_HASH_SALT||"volleybal-sync";const hash=crypto.createHash("sha256").update(salt+"|"+key).digest("hex");return {partitionKey:team.toLowerCase(),rowKey:hash};}
async function ensure(c){try{await c.createTable();}catch(e){if(e.statusCode!==409)throw e;}}
app.http("sync",{methods:["GET","PUT","OPTIONS"],authLevel:"anonymous",route:"sync",handler:async(req,ctx)=>{try{if(req.method==="OPTIONS")return{status:204};const id=identity(req);if(!id)return{status:400,jsonBody:{error:"Team-ID en synchronisatiecode van minimaal 8 tekens zijn vereist."}};const c=client();await ensure(c);if(req.method==="GET"){try{const e=await c.getEntity(id.partitionKey,id.rowKey);return{jsonBody:{bundle:JSON.parse(e.payload),updatedAt:e.updatedAt}};}catch(e){if(e.statusCode===404)return{status:404,jsonBody:{error:"Nog geen cloudgegevens voor deze combinatie."}};throw e;}}const bundle=await req.json();if(!bundle||typeof bundle!=="object")return{status:400,jsonBody:{error:"Ongeldige synchronisatiegegevens."}};const payload=JSON.stringify(bundle);if(Buffer.byteLength(payload,"utf8")>60000)return{status:413,jsonBody:{error:"Synchronisatiegegevens zijn te groot."}};const updatedAt=new Date().toISOString();await c.upsertEntity({...id,payload,updatedAt,schemaVersion:1},"Replace");return{jsonBody:{ok:true,updatedAt}};}catch(e){ctx.error(e);return{status:500,jsonBody:{error:"Cloudsynchronisatie is niet beschikbaar."}};}}});
